chore: add go-licence-detector script and tool

diff --git a/Makefile.Common b/Makefile.Common
--- a/Makefile.Common
+++ b/Makefile.Common
@@ -89,6 +89,7 @@ GCI                 := $(TOOLS_BIN_DIR)/gci
 GOTESTSUM           := $(TOOLS_BIN_DIR)/gotestsum
 CHECKAPI            := $(TOOLS_BIN_DIR)/checkapi
 MODERNIZE           := $(TOOLS_BIN_DIR)/modernize
+LICENSE_DETECTOR	:= $(TOOLS_BIN_DIR)/go-licence-detector
 
 # Tools used by go generate commands
 MDATAGEN := $(TOOLS_BIN_DIR)/mdatagen
@@ -358,3 +359,16 @@ run-changed-tests:
 			done \
 		fi \
 	fi
+
+.PHONY: thirdparty
+thirdparty: OUT ?= THIRD_PARTY_NOTICES.md
+thirdparty: $(LICENSE_DETECTOR) ## Runs go generate for the current module.
+	@test -f $(LICENSE_DETECTOR) || (echo "go-licence-detector not found, run 'make install-tools' from the base directory" && exit 1)
+	$(GOCMD) list -mod=mod -m -json all | $(LICENSE_DETECTOR) \
+        -rules $(SRC_ROOT)/internal/assets/license/rules.json \
+        -noticeTemplate $(SRC_ROOT)/internal/assets/license/THIRD_PARTY_NOTICES.md.tmpl \
+        -noticeOut $(OUT)
+
+.PHONY: checkthirdparty
+checkthirdparty: thirdparty
+	@git diff --name-only | grep -q "THIRD_PARTY_NOTICES.md" && { echo "Third party notices out of date, please run \"make thirdparty\" and commit the changes in this PR."; exit 1; } || exit 0
