refactor: consolidate license generation tasks

diff --git a/Makefile.Common b/Makefile.Common
--- a/Makefile.Common
+++ b/Makefile.Common
@@ -330,7 +330,6 @@ HEADER_APACHE=$(SRC_ROOT)/internal/assets/license/nr_header_apache.tmpl
 HEADER_PROPRIETARY=$(SRC_ROOT)/internal/assets/license/nr_header_proprietary.tmpl
 LICENSE_APACHE=$(SRC_ROOT)/internal/assets/license/LICENSE_APACHE.tmpl
 LICENSE_PROPRIETARY=$(SRC_ROOT)/internal/assets/license/LICENSE_NEW_RELIC.tmpl
-
 .PHONY: generate-component-license
 generate-component-license:
 	@component_path="$$(pwd | sed 's|^$(SRC_ROOT)/||')"; \
@@ -353,79 +352,50 @@ generate-component-license:
 		done; \
 	); \
 	if [ -n "$${res}" ]; then \
-		echo "license header checking failed:"; echo "$${res}"; \
-		echo "Run \"make component-replace-license-headers\" if adding new files."; \
+		echo "❌ License generation failed for $$component_path"; echo "$${res}"; \
 		exit 1; \
 	else \
 		echo "✅ License generated for $$component_path"; \
 	fi
-	
-.PHONY: check-license-headers
-check-license-headers: $(ADDLICENSE)
-	@licRes=$$(for f in $$($(ALL_SRC_AND_SHELL_CMD)); do \
-		if awk '/generated|GENERATED/ && NR<=3 { found=1; exit } END { if (!found) exit 1 }' $$f; then \
-			continue; \
-		fi; \
-		component_path="$$(realpath $$f | sed 's|^$(SRC_ROOT)/||' | cut -d'/' -f1-2)"; \
+
+.PHONY: check-component-license
+check-component-license:
+	@component_path="$$(pwd | sed 's|^$(SRC_ROOT)/||')"; \
+	res=$$( \
 		is_proprietary=$$(cat "$(SRC_ROOT)/LICENSING" | grep $$component_path); \
 		if [ -n "$$is_proprietary" ]; then \
-			proprietary_header=$$(cat $(SRC_ROOT)/internal/assets/license/nr_header_proprietary.tmpl); \
-			if ! grep -qF "$$proprietary_header" $$f; then \
-				echo -e "$$f  --  wrong or missing license header. Expected NR software license."; \
-			fi; \
-			continue; \
-		fi; \
-		if awk '/Copyright/ && NR<=3 { found=1; next } END { if (!found) print FILENAME "  --  missing copyright." }' $$f; then \
-			continue; \
-		fi; \
-		if awk '/SPDX-License-Identifier:/ && NR<=4 { found=1; next } END { if (!found) print FILENAME "  --  missing SPDX identifier." }' $$f; then \
-			continue; \
-		fi; \
-		$(ADDLICENSE_CMD) -check "$$f" 2>&1 || echo "$$f"; \
-		done); \
-	if [ -n "$${licRes}" ]; then \
-		echo "license header checking failed:"; echo "$${licRes}"; \
-		echo "Run \"make component-replace-license-headers\" if adding new files."; \
-		exit 1; \
-	else \
-		echo "✅ License headers valiated."; \
-	fi
-
-.PHONY: check-component-license-file
-check-component-license-file:
-	@checkFileRes=$$( \
-		component_path="$$(pwd | sed 's|^$(SRC_ROOT)/||')"; \
-		license=$$(basename $$(find "." -maxdepth 1 -type f -iname "LICENSE*") 2>/dev/null); \
-        if [ -z "$$license" ]; then \
-            echo "No license file found in $$component_path"; \
-			exit 1; \
-        fi; \
-		licensing_file_entry=$$(cat ${SRC_ROOT}/LICENSING | grep "$$component_path"); \
-        if [[ "$$license" == "LICENSE_NEW_RELIC"* ]]; then \
-            if [ ! -n "$$licensing_file_entry" ]; then \
-                echo "Component with propietary license $$component_path not listed in LICENSING"; \
-				exit 1; \
-            fi; \
-			NEW_RELIC_SOFTWARE_LICENSE="$$(cat ${SRC_ROOT}/internal/assets/license/LICENSE_NEW_RELIC_component.tmpl)"; \
-            if [[ ! "$$(cat "$$license")" == "$$NEW_RELIC_SOFTWARE_LICENSE" ]]; then \
-                echo "LICENSE file in $$component_path does not contain the correct New Relic Software License text."; \
-				exit 1; \
-            fi; \
+			expected_license_filename="LICENSE_NEW_RELIC_$$(basename $$component_path)"; \
+			expected_license_contents="$$(cat $(LICENSE_PROPRIETARY))"; \
+			expected_header="$$(cat $(HEADER_PROPRIETARY))"; \
 		else \
-			if [ -n "$$licensing_file_entry" ]; then \
-                echo "Component $$component_path listen in LICENSING as proprietary has incorrect license type: $$license"; \
-				exit 1; \
-            fi; \
-        fi);\
-	if [ -n "$${checkFileRes}" ]; then \
-		echo "❌ License file check failed:"; echo "$${checkFileRes}"; \
+			expected_license_filename="LICENSE_APACHE_$$(basename $$component_path)"; \
+			expected_license_contents="$$(cat $(LICENSE_APACHE))"; \
+			expected_header="$$(cat $(HEADER_APACHE))"; \
+		fi; \
+		license=$$(basename $$(find "." -maxdepth 1 -type f -iname "LICENSE*") 2>/dev/null); \
+		if [ -z "$$license" ]; then \
+            echo "   - No license file found."; \
+		else \
+			if [ ! "$$license" = "$$expected_license_filename" ]; then echo -e "   - License \"$$license\" has incorrect file name. Expected \"$$expected_license_filename\"."; fi; \
+			if [ ! "$$(cat $$license)" = "$$expected_license_contents" ]; then echo -e "   - License \"$$license\" has incorrect license text."; fi; \
+        fi; \
+		for f in $$($(ALL_SRC_AND_SHELL_CMD)); do \
+			if awk '/generated|GENERATED/ && NR<=3 { found=1; exit } END { if (!found) exit 1 }' $$f; then \
+				continue; \
+			fi; \
+			grep -qF "$$expected_header" $$f || echo "   - File \"$$f\" has incorrect or missing license header"; \
+		done; \
+	); \
+	if [ -n "$${res}" ]; then \
+		echo "❌ License validation failed for $$component_path:"; echo "$${res}"; \
+		echo -e "ℹ️  Run \"make generate-all-component-licenses\" to fix license issues and generate licenses."; \
 		exit 1; \
 	else \
-		echo "✅ Valid license file in $$(pwd | sed 's|^$(SRC_ROOT)/||')."; \
+		echo "✅ License validated for $$component_path"; \
 	fi
 
-.PHONY: validate-licensing
-validate-licensing:
+.PHONY: validate-licensing-file
+validate-licensing-file:
 	@res=$$( \
 		components_in_LICENSING=$$(cat ${ROOT_DIR}/LICENSING | grep '^[[:space:]]*-' | sed 's/^[[:space:]]*-[[:space:]]//'); \
 		for component_path in $$components_in_LICENSING; do \
