refactor: treat LICENSING as source of truth instead of separate .yaml

diff --git a/Makefile.Common b/Makefile.Common
--- a/Makefile.Common
+++ b/Makefile.Common
@@ -203,65 +203,6 @@ do-integration-tests-with-cover: $(GOTESTSUM)
 benchmark: $(GOTESTSUM)
 	$(GOTESTSUM) $(GOTESTSUM_OPT) --packages="$$(find . -name 'go.mod' -not -path '*/third_party/*' -not -path '*/local/*' -type f | xargs dirname | sort | uniq | xargs -L 1 bash -c 'cd $$0 && go list -f "{{ .Dir }}"' | xargs echo)" -- -bench=. -run=notests --tags=$(GO_BUILD_TAGS)
 
-.PHONY: remove-license-headers
-remove-license-headers:
-	@REMOVELICENSEOUT=$$(for f in $$($(ALL_SRC_AND_SHELL_CMD)); do \
-		if awk '/generated|GENERATED/ && NR<=3 { found=1; exit 0 } END { exit !found }' $$f; then \
-			continue; \
-		fi; \
-		if head -n 4 $$f | grep -q 'Copyright' && head -n 4 $$f | grep -q 'SPDX'; then \
-			tail -n +4 $$f > $$f.tmp && mv $$f.tmp $$f; \
-			continue; \
-		fi; \
-	done); \
-	if [ "$$REMOVELICENSEOUT" ]; then \
-		echo " FAILED => remove License errors:\n"; \
-		echo "$$REMOVELICENSEOUT\n"; \
-		exit 1; \
-	else \
-		echo "Remove license finished successfully"; \
-	fi
-
-.PHONY: add-license-headers
-add-license-headers: $(ADDLICENSE)
-	@ADDLICENSEOUT=$$(for f in $$($(ALL_SRC_AND_SHELL_CMD)); do \
-		component_dir="$$(realpath $$f | sed 's|^$(SRC_ROOT)/||' | cut -d'/' -f1-2)"; \
-		is_proprietary=$$(dir=$$component_dir yq '.new_relic[] | select(. == strenv(dir))' $(SRC_ROOT)/component_licenses.yaml); \
-		if [ -n "$$is_proprietary" ]; then \
-			`$(ADDLICENSE_CMD_NR_PROPRIETARY) "$$f" 2>&1`; \
-		else \
-			`$(ADDLICENSE_CMD_NR_APACHE) "$$f" 2>&1`; \
-		fi; \
-	done); \
-	if [ "$$ADDLICENSEOUT" ]; then \
-		echo "$(ADDLICENSE) FAILED => add License errors:\n"; \
-		echo "$$ADDLICENSEOUT\n"; \
-		exit 1; \
-	else \
-		echo "Add License finished successfully"; \
-	fi
-
-.PHONY: replace-license-headers
-replace-license-headers: remove-license-headers add-license-headers
-
-.PHONY: check-license-headers
-check-license-headers: $(ADDLICENSE)
-	@licRes=$$(for f in $$($(ALL_SRC_AND_SHELL_CMD)); do \
-		if awk '/Copyright|generated|GENERATED/ && NR<=3 { found=1; next } END { if (!found) print FILENAME }' $$f; then \
-			continue; \
-		fi; \
-		if awk '/SPDX-License-Identifier:|generated|GENERATED/ && NR<=4 { found=1; next } END { if (!found) print FILENAME }' $$f; then \
-			continue; \
-		fi; \
-		$(ADDLICENSE_CMD) -check "$$f" 2>&1 || echo "$$f"; \
-		done); \
-	if [ -n "$${licRes}" ]; then \
-		echo "license header checking failed:"; echo "$${licRes}"; \
-		exit 1; \
-	else \
-		echo "Check License finished successfully"; \
-	fi
-
 .PHONY: checklinks
 checklinks:
 	command -v $(DOCKERCMD) >/dev/null 2>&1 || { echo >&2 "$(DOCKERCMD) not installed. Install before continuing"; exit 1; }
@@ -387,4 +328,84 @@ run-changed-tests:
 				$(GOTESTSUM) --packages="./..." -- $(GOTEST_OPT) -count=3 ); \
 			done \
 		fi \
+	fi
+
+.PHONY: add-license-headers
+add-license-headers: $(ADDLICENSE)
+	@ADDLICENSEOUT=$$(for f in $$($(ALL_SRC_AND_SHELL_CMD)); do \
+		component_dir="$$(realpath $$f | sed 's|^$(SRC_ROOT)/||' | cut -d'/' -f1-2)"; \
+		is_proprietary=$$(cat "$(SRC_ROOT)/LICENSING" | grep $$component_dir); \
+		if [ -n "$$is_proprietary" ]; then \
+			`$(ADDLICENSE_CMD_NR_PROPRIETARY) "$$f" 2>&1`; \
+		else \
+			`$(ADDLICENSE_CMD_NR_APACHE) "$$f" 2>&1`; \
+		fi; \
+	done); \
+	if [ "$$ADDLICENSEOUT" ]; then \
+		echo "$(ADDLICENSE) FAILED => add License errors:\n"; \
+		echo "$$ADDLICENSEOUT\n"; \
+		exit 1; \
+	else \
+		echo "Add License finished successfully"; \
+	fi
+
+.PHONY: remove-license-headers
+remove-license-headers:
+	@REMOVELICENSEOUT=$$(for f in $$($(ALL_SRC_AND_SHELL_CMD)); do \
+		if awk '/generated|GENERATED/ && NR<=3 { found=1; exit 0 } END { exit !found }' $$f; then \
+			continue; \
+		fi; \
+		if head -n 4 $$f | grep -q 'Copyright' && head -n 4 $$f | grep -q 'SPDX'; then \
+			tail -n +4 $$f > $$f.tmp && mv $$f.tmp $$f; \
+			continue; \
+		fi; \
+	done); \
+	if [ "$$REMOVELICENSEOUT" ]; then \
+		echo " FAILED => remove License errors:\n"; \
+		echo "$$REMOVELICENSEOUT\n"; \
+		exit 1; \
+	else \
+		echo "Remove license finished successfully"; \
+	fi
+
+.PHONY: replace-license-headers
+replace-license-headers: remove-license-headers add-license-headers
+
+.PHONY: check-license-headers
+check-license-headers: $(ADDLICENSE)
+	@licRes=$$(for f in $$($(ALL_SRC_AND_SHELL_CMD)); do \
+		if awk '/Copyright|generated|GENERATED/ && NR<=3 { found=1; next } END { if (!found) print FILENAME }' $$f; then \
+			continue; \
+		fi; \
+		if awk '/SPDX-License-Identifier:|generated|GENERATED/ && NR<=4 { found=1; next } END { if (!found) print FILENAME }' $$f; then \
+			continue; \
+		fi; \
+		$(ADDLICENSE_CMD) -check "$$f" 2>&1 || echo "$$f"; \
+		done); \
+	if [ -n "$${licRes}" ]; then \
+		echo "license header checking failed:"; echo "$${licRes}"; \
+		exit 1; \
+	else \
+		echo "Check License finished successfully"; \
+	fi
+
+.PHONY: add-license-files
+add-license-files:
+	@filesRes=$$( \
+		component_dir="$$(pwd | sed 's|^$(SRC_ROOT)/||')"; \
+		is_proprietary=$$(cat "$(SRC_ROOT)/LICENSING" | grep $$component_dir); \
+		if [ -n "$$is_proprietary" ]; then \
+			proprietary_license=$$(cat $(SRC_ROOT)/internal/assets/license/LICENSE_NEW_RELIC_component.tmpl); \
+			cat $$proprietary_license > "LICENSE_NEW_RELIC_$$component_dir" 2>&1; \
+		else \
+			apache_license=$$(cat $(SRC_ROOT)/internal/assets/license/LICENSE_APACHE_component.tmpl); \
+			cat $$apache_license > "LICENSE_APACHE_$$component_dir" 2>&1; \
+		fi); \
+	component_dir="$$(pwd | sed 's|^$(SRC_ROOT)/||')"; \
+	echo "$$component_dir"; \
+	if [ -n "$${filesRes}" ]; then \
+		echo "License file add failed:"; echo "$${licRes}"; \
+		exit 1; \
+	else \
+		echo "Added license file successfuly."; \
 	fi
